services:
  birdlens-db:
    image: postgres:17.5
    ports:
      - "5431:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: birdlens
    volumes:
      - db-data:/var/lib/postgresql/data

  birdlens-be:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - birdlens-db
    restart: always
    environment:
      DB_ADDR: postgres://admin:password@birdlens-db:5432/birdlens?sslmode=disable
      HTTP_PORT: 8080
      ENV: "dev"
      ACCESS_TOKEN_EXP_MIN: 10
      REFRESH_TOKEN_EXP_DAY : 14
    deploy:
      mode: replicated
      replicas: 3

  nginx:
    image: nginx:1.27
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - birdlens-be
    restart: always

volumes:
  db-data:
