services:
  birdlens-db:
    image: postgres:17.5
    ports:
      - "5431:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: birdlens
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - birdlens-network

  birdlens-be:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - birdlens-db
    restart: always
    environment:
      DB_ADDR: postgres://${DB_USER}:${DB_PASSWORD}@birdlens-db:5432/birdlens?sslmode=disable
      HTTP_PORT: 6969
      ENV: "dev"
      ACCESS_TOKEN_EXP_MIN: 10 
      REFRESH_TOKEN_EXP_DAY: 14 
      PATH_TO_FIREBASE_CREDS: /env/birdlens-creds.json
      BASE_URL: "http://localhost"
      EMAIL_VERIFICATION_EXPIRES_IN_HOURS: ${EMAIL_VERIFICATION_EXPIRES_IN_HOURS:-24}
      # And FRONTEND_URL, though not used for this specific feature, is read by main.go
      FRONTEND_URL: ${FRONTEND_URL:-"birdlens://deeplink"}
      # JWT_SECRET_KEY, SMTP variables will be loaded by the Go app from /env/mail.env and /env/.env if present there.
      # If not, and if critical, they should be explicitly set here or ensure the .env files in the image are correct.
      # Example: JWT_SECRET_KEY: ${JWT_SECRET_KEY:?"JWT_SECRET_KEY must be set in .env or here"}


    deploy:
      mode: replicated
      replicas: 3
    networks:
      - birdlens-network

  migrate:
    image: migrate/migrate:4
    volumes:
      - ./cmd/migrate/migrations/:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${DB_USER}:${DB_PASSWORD}@birdlens-db:5432/birdlens?sslmode=disable",
        "up",
      ]
    depends_on: 
      - birdlens-db
    networks:
      - birdlens-network

  nginx:
    image: nginx:1.27
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - birdlens-be
    restart: always
    networks:
      - birdlens-network

  mailpit:
    image: axllent/mailpit:v1.26
    container_name: mock-mail
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped
    environment:
      MP_SMTP_TLS_CERT: /env/cert.pem
      MP_SMTP_TLS_KEY: /env/key.pem
      MP_SMTP_REQUIRE_TLS: "false"
    networks:
      - birdlens-network
    volumes:
      - ./env:/env

volumes:
  db-data:

networks:
  birdlens-network:
    external: true