services:
  birdlens-db:
    image: postgres:17.5
    ports:
      - "5431:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: birdlens
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - birdlens-network

  birdlens-be:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - birdlens-db
    restart: always
    env_file:
      - ./env/.env 
    environment:
      DB_ADDR: postgres://${DB_USER}:${DB_PASSWORD}@birdlens-db:5432/birdlens?sslmode=disable
      HTTP_PORT: 6969
      ENV: "dev"
      ACCESS_TOKEN_EXP_MIN: 10 
      REFRESH_TOKEN_EXP_DAY: 14 
      PATH_TO_FIREBASE_CREDS: /env/birdlens-creds.json
      
    deploy:
      mode: replicated
      replicas: 1 # MODIFIED FROM 3 to 1
    networks:
      - birdlens-network

  migrate:
    image: migrate/migrate:4
    volumes:
      - ./cmd/migrate/migrations/:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${DB_USER}:${DB_PASSWORD}@birdlens-db:5432/birdlens?sslmode=disable",
        "up",
      ]
    depends_on: 
      - birdlens-db
    networks:
      - birdlens-network

  nginx:
    image: nginx:1.27
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - birdlens-be
    restart: always
    networks:
      - birdlens-network

  mailpit:
    image: axllent/mailpit:v1.26
    container_name: mock-mail
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped
    environment:
      MP_SMTP_TLS_CERT: /env/cert.pem
      MP_SMTP_TLS_KEY: /env/key.pem
      MP_SMTP_REQUIRE_TLS: "false"
    networks:
      - birdlens-network
    volumes:
      - ./env:/env

volumes:
  db-data:

networks:
  birdlens-network:
    external: true