# birdlens-be/docker-compose.yml
services:
  birdlens-db:
    image:  postgis/postgis:17-3.5-alpine
    ports:
      - "5431:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: birdlens
    volumes:
      - db-data:/var/lib/postgresql/data
    # Logic: The healthcheck command is updated to use the standard environment variables
    # that exist *inside* the PostgreSQL container ($POSTGRES_USER). This is more
    # reliable than relying on Docker Compose's substitution from the host.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - birdlens-network

  birdlens-be:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      birdlens-db:
        condition: service_healthy
    restart: always
    env_file:
      - ./env/.env
      - ./env/ebird.env
      - ./env/gemini.env
    environment:
      DB_ADDR: postgres://${DB_USER}:${DB_PASSWORD}@birdlens-db:5432/birdlens?sslmode=disable
      HTTP_PORT: 6969
      ENV: "dev"
      ACCESS_TOKEN_EXP_MIN: 10
      REFRESH_TOKEN_EXP_DAY: 14
      PATH_TO_FIREBASE_CREDS: /env/birdlens-creds.json
      
    deploy:
      mode: replicated
      replicas: 1 # MODIFIED FROM 3 to 1
    networks:
      - birdlens-network

  migrate:
    image: migrate/migrate:4
    volumes:
      - ./cmd/migrate/migrations/:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${DB_USER}:${DB_PASSWORD}@birdlens-db:5432/birdlens?sslmode=disable",
        "up",
      ]
    depends_on: 
      birdlens-db:
        condition: service_healthy
    networks:
      - birdlens-network

  nginx:
    image: nginx:1.27
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - birdlens-be
    restart: always
    networks:
      - birdlens-network

  mailpit:
    image: axllent/mailpit:v1.26
    container_name: mock-mail
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped
    environment:
      MP_SMTP_TLS_CERT: /env/cert.pem
      MP_SMTP_TLS_KEY: /env/key.pem
      MP_SMTP_REQUIRE_TLS: "false"
    networks:
      - birdlens-network
    volumes:
      - ./env:/env

volumes:
  db-data:

networks:
  birdlens-network:
    external: true