ALTER TABLE tours
ADD COLUMN name VARCHAR(255) NOT NULL,
ADD COLUMN description TEXT NOT NULL,
ADD COLUMN thumbnail_url VARCHAR(255),
ADD COLUMN duration INT NOT NULL,
ADD COLUMN start_date TIMESTAMP(0) WITH TIME ZONE NOT NULL,
ADD COLUMN end_date TIMESTAMP(0) WITH TIME ZONE NOT NULL,
ADD COLUMN location_id BIGINT NOT NULL,
ADD COLUMN created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
ADD COLUMN updated_at TIMESTAMP(0) WITH TIME ZONE,
ADD CONSTRAINT fk_location FOREIGN KEY (location_id) REFERENCES location(id) ON DELETE CASCADE;
